[tool.pdm]

[tool.pdm.scripts]
start = "flask --app asim_flashcards run --debug"

[project]
description = ""
dependencies = [
    "flask>=2.2.3",
    "pymongo>=4.3.3",
    "python-dotenv>=1.0.0",
    "bcrypt>=4.0.1",
]
requires-python = ">=3.10"
