[tool.pdm]

[tool.pdm.scripts]
start = "flask --app asim_flashcards run --debug"

[project]
name = "asim_flashcards"
version = "0.1.0"
description = ""
dependencies = [
    "flask>=2.2.3",
]
requires-python = ">=3.10"
